### ISSUE TITLE
Fail to find optimal solution for this example

### ISSUE THREAD

**Issue by Gnimuc** [opensourcesblog/hungarian#1]
I didn't dig into the code, just found a corner case:
```julia
A = UInt8[198 209  93  81 199 184 206 161   5 171 195 199 116  13 247;
           69   7  54  33 246 196 196 195  20 128   9 109  86 213 131;
           65 155  52 148 202 254  18 161  43  77 118 109  96  75 177;
           61  62 181 136 226 113 109 228  66  85  43 253 105 170  83;
          227 225 219 228  44 230  85   1   7  48  65 171  23  33 125;
           90 123 188  58 173 130 252  99 225 198 243 255 243 144 241;
          110  96  27 239 251 174 136  27 254 198  33  24 215  11 149;
           54  99 236 104 191 208  70 129 207 213 156 227 213 158 239;
          246 239 229 159 221 142   5 115 150 233  83 251  82  14  47;
           11 162 238 167 189  77  16  46 202 216  81  11 104 255  87;
          195 140 110 124 215 221 101  52 163  37  52  13 158 229 237;
          106 241 101 178 127 139  42 145 151  53 171 230 102  91 127;
            3  89 141 169 238 166 233  66  93 242  48  70 105  97  73;
          188 199 255 197 114   6  32  91  27 141 152 202 164   0 185;
          199  68  26 103 195  88  99 188 113 104 199  63  89  89 234]
```

```julia
using Hungarian
include("hungarian.jl")
using Munkres

n = 15
hh = Hungarian.munkres(A)
match_h = [findfirst(hh[i,:].==Hungarian.STAR) for i = 1:n]
match_m = munkres(A)
match_own = run_hungarian(A)

sum_own = 0.0
c = 1
for r in match_own
 sum_own += A[r,c]
 c += 1
end
sum_own  #-> 781

sum_h = sum(A[ii, match_h[ii]] for ii in 1:n) |> Int    #-> 525
sum_m = sum(A[ii, match_m[ii]] for ii in 1:n) |> Int    #-> 525
```
However, everything works fine when `A` is of type `>:Int16`, a wild guess is something wrong with integer arithmetics.

**Comment by Wikunia** [comment]
Thanks for the issue. Yes I didn't mention this inside my blog post or somewhere else. I had the same issue  but it makes sense. Don't know how your algorithm works. In mine I add something to some entries in the matrix and then there is an overflow which ruins everything. That's the reason why I'm using the line in the benchmark code which checks whether there are values over 50,000. BTW I noticed something similar with your algorithm just in different cases.

**Comment by Gnimuc** [comment]
yeah, the reason is integer overflow, a quick fix would be to promote the eltype of the cost matrix using `widen`:
```julia
B = copy(A) |> Array{widen(eltype(A))}
```
This will make every entry in B of type `UInt32`, but I guess this is too much safer, `UInt16` is ok in this example.

**Comment by Wikunia** [comment]
Hmm yes that's true. Thanks for the example. I'm still a beginner in julia. That small snippet looks fantastic to me.
